export enum Status {
  STARTED = 'STARTED',
  SCHEMA_ERRORS = 'SCHEMA_ERRORS',
  PROCESSING = 'PROCESSING',
  PROCESSED_WITH_SUCCESS = 'PROCESSED_WITH_SUCCESS',
  PROCESSED_WITH_ERRORS = 'PROCESSED_WITH_ERRORS',
}
